# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('image_nm', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
