# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_image_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('text_post', models.CharField(max_length=550)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
