# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0005_police_drug_info_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer_info_tb',
            name='ipaddr',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='police_drug_info_tb',
            name='ipaddr',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='register_tb',
            name='ipaddr',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
