# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-04 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0006_auto_20190827_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_drug_info_tb',
            name='status',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
